export const mockStudents = [
  {
    id: "1",
    name: "Priya Sharma",
    photo: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "Retail Sales",
    center: "Mumbai Central",
    city: "Mumbai",
    jobPreference: "Sales Executive",
    salaryExpectation: "₹18,000",
    status: "Placed",
    email: "priya.sharma@email.com",
    phone: "+91 98765 43210",
    gender: "Female",
    dob: "1999-05-12",
    address: "B-204, Andheri West, Mumbai",
    zone: "West",
    education: "12th Pass",
    skills: ["Communication", "Customer Service", "MS Office"],
    certificates: ["Retail Sales - Level 2", "Customer Handling"],
    company: "Reliance Retail",
    joinDate: "2024-01-15",
    salary: "₹20,000",
  },
  {
    id: "2",
    name: "Rahul Verma",
    photo: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "BPO / Customer Support",
    center: "Delhi East",
    city: "Delhi",
    jobPreference: "Customer Support Executive",
    salaryExpectation: "₹22,000",
    status: "Interview",
    email: "rahul.verma@email.com",
    phone: "+91 87654 32109",
    gender: "Male",
    dob: "2000-08-20",
    address: "Sector 12, Rohini, Delhi",
    zone: "North",
    education: "Graduate",
    skills: ["English Communication", "Typing", "Problem Solving"],
    certificates: ["BPO Fundamentals"],
    company: null,
    joinDate: null,
    salary: null,
  },
  {
    id: "3",
    name: "Anjali Patel",
    photo: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "Beauty & Wellness",
    center: "Pune West",
    city: "Pune",
    jobPreference: "Beauty Therapist",
    salaryExpectation: "₹16,000",
    status: "Shortlisted",
    email: "anjali.patel@email.com",
    phone: "+91 76543 21098",
    gender: "Female",
    dob: "2001-02-14",
    address: "Kothrud, Pune",
    zone: "West",
    education: "10th Pass",
    skills: ["Skincare", "Makeup", "Hair Styling"],
    certificates: ["Beauty & Wellness - Level 1"],
    company: null,
    joinDate: null,
    salary: null,
  },
  {
    id: "4",
    name: "Mohammed Iqbal",
    photo: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "Electrical Work",
    center: "Hyderabad South",
    city: "Hyderabad",
    jobPreference: "Electrician",
    salaryExpectation: "₹20,000",
    status: "Placed",
    email: "iqbal.m@email.com",
    phone: "+91 65432 10987",
    gender: "Male",
    dob: "1998-11-30",
    address: "Malakpet, Hyderabad",
    zone: "South",
    education: "ITI",
    skills: ["Wiring", "Panel Installation", "Safety Protocols"],
    certificates: ["Electrician - Level 3"],
    company: "L&T Construction",
    joinDate: "2024-02-01",
    salary: "₹22,000",
  },
  {
    id: "5",
    name: "Sunita Kumari",
    photo: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "Healthcare",
    center: "Chennai North",
    city: "Chennai",
    jobPreference: "General Duty Assistant",
    salaryExpectation: "₹15,000",
    status: "Applied",
    email: "sunita.k@email.com",
    phone: "+91 54321 09876",
    gender: "Female",
    dob: "2000-07-08",
    address: "Perambur, Chennai",
    zone: "South",
    education: "12th Pass",
    skills: ["Patient Care", "First Aid", "Hygiene Management"],
    certificates: ["Healthcare Assistant - Level 1"],
    company: null,
    joinDate: null,
    salary: null,
  },
  {
    id: "6",
    name: "Vikram Singh",
    photo: "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "Logistics & Warehousing",
    center: "Kolkata Central",
    city: "Kolkata",
    jobPreference: "Warehouse Supervisor",
    salaryExpectation: "₹25,000",
    status: "Retained",
    email: "vikram.s@email.com",
    phone: "+91 43210 98765",
    gender: "Male",
    dob: "1997-03-25",
    address: "Behala, Kolkata",
    zone: "East",
    education: "Graduate",
    skills: ["Inventory Management", "Forklift Operation", "SAP Basics"],
    certificates: ["Logistics - Level 2"],
    company: "Amazon India",
    joinDate: "2023-09-01",
    salary: "₹27,000",
  },
  {
    id: "7",
    name: "Divya Nair",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "Retail Sales",
    center: "Bangalore South",
    city: "Bangalore",
    jobPreference: "Store Manager Trainee",
    salaryExpectation: "₹20,000",
    status: "Seeking",
    email: "divya.n@email.com",
    phone: "+91 32109 87654",
    gender: "Female",
    dob: "2001-09-17",
    address: "Jayanagar, Bangalore",
    zone: "South",
    education: "Graduate",
    skills: ["Sales", "Visual Merchandising", "Team Leadership"],
    certificates: ["Retail Management - Level 2"],
    company: null,
    joinDate: null,
    salary: null,
  },
  {
    id: "8",
    name: "Arjun Tiwari",
    photo: "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=100",
    course: "IT / Data Entry",
    center: "Lucknow Central",
    city: "Lucknow",
    jobPreference: "Data Entry Operator",
    salaryExpectation: "₹14,000",
    status: "Placed",
    email: "arjun.t@email.com",
    phone: "+91 21098 76543",
    gender: "Male",
    dob: "2000-12-01",
    address: "Gomti Nagar, Lucknow",
    zone: "North",
    education: "12th Pass",
    skills: ["Typing (50 WPM)", "MS Excel", "Tally"],
    certificates: ["Computer Basics", "Tally ERP 9"],
    company: "HDFC Bank",
    joinDate: "2024-03-10",
    salary: "₹15,500",
  },
];

export const mockJobs = [
  {
    id: "1",
    title: "Retail Sales Executive",
    company: "Reliance Retail",
    logo: "https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=60",
    location: "Mumbai",
    salary: "₹18,000 – ₹22,000",
    experience: "0–1 Year",
    category: "Retail",
    tags: ["Sales", "Customer Service", "Fresher OK"],
    description: "We are looking for energetic retail sales executives to join our growing team at Reliance Retail stores across Mumbai. You will be responsible for customer engagement, product demonstration, and achieving daily sales targets.",
    requirements: ["10th or 12th Pass", "Good communication skills", "Willingness to work in shifts", "Basic computer knowledge"],
    benefits: ["PF & ESI", "Performance Bonus", "Employee Discount", "Growth Opportunities"],
    posted: "2 days ago",
    openings: 15,
    type: "Full Time",
  },
  {
    id: "2",
    title: "Customer Support Executive",
    company: "Concentrix",
    logo: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=60",
    location: "Delhi",
    salary: "₹20,000 – ₹25,000",
    experience: "0–2 Years",
    category: "BPO",
    tags: ["BPO", "English", "Night Shift Allowance"],
    description: "Join our world-class customer support team and help customers resolve their queries via phone and chat. Extensive training provided.",
    requirements: ["Graduate or 12th Pass", "Excellent English communication", "Flexible to work in shifts", "Basic computer skills"],
    benefits: ["Cab Facility", "Night Shift Allowance", "PF & ESI", "Incentives"],
    posted: "1 day ago",
    openings: 30,
    type: "Full Time",
  },
  {
    id: "3",
    title: "General Duty Assistant",
    company: "Apollo Hospitals",
    logo: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=60",
    location: "Chennai",
    salary: "₹14,000 – ₹18,000",
    experience: "0–1 Year",
    category: "Healthcare",
    tags: ["Healthcare", "Fresher", "Night Duty"],
    description: "Provide basic patient care under supervision of nursing staff. Maintain hygiene and assist in ward management.",
    requirements: ["10th Pass minimum", "Healthcare training certificate preferred", "Physical fitness", "Compassionate attitude"],
    benefits: ["Uniform Provided", "Meals", "PF & ESI", "Career Growth in Healthcare"],
    posted: "3 days ago",
    openings: 10,
    type: "Full Time",
  },
  {
    id: "4",
    title: "Electrician – Site",
    company: "L&T Construction",
    logo: "https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=60",
    location: "Hyderabad",
    salary: "₹20,000 – ₹28,000",
    experience: "1–3 Years",
    category: "Electrical",
    tags: ["ITI", "Site Work", "Skilled Trade"],
    description: "We need certified electricians for our construction projects. You will handle wiring, panel installation, and electrical maintenance on-site.",
    requirements: ["ITI in Electrician trade", "NSDC certification preferred", "Safety training", "1+ year experience"],
    benefits: ["Site Allowance", "Safety Equipment Provided", "Overtime Pay", "PF & ESI"],
    posted: "5 days ago",
    openings: 8,
    type: "Full Time",
  },
  {
    id: "5",
    title: "Beauty Therapist",
    company: "VLCC Wellness",
    logo: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=60",
    location: "Pune",
    salary: "₹15,000 – ₹20,000",
    experience: "0–2 Years",
    category: "Beauty & Wellness",
    tags: ["Beauty", "Wellness", "Female Preferred"],
    description: "Provide a range of beauty and wellness services to clients including facials, body treatments, and hair styling in a professional salon environment.",
    requirements: ["Beauty & Wellness certificate", "Good grooming", "Customer-friendly attitude", "Knowledge of skin types"],
    benefits: ["Tips Included", "Product Training", "Performance Bonus", "Weekend Off Option"],
    posted: "1 week ago",
    openings: 5,
    type: "Full Time",
  },
  {
    id: "6",
    title: "Warehouse Associate",
    company: "Amazon India",
    logo: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=60",
    location: "Kolkata",
    salary: "₹22,000 – ₹28,000",
    experience: "0–2 Years",
    category: "Logistics",
    tags: ["Warehouse", "Logistics", "Physical Work"],
    description: "Join Amazon's fulfillment team and be part of the world's most customer-centric company. Handle inbound/outbound operations efficiently.",
    requirements: ["10th Pass", "Physical fitness", "Ability to work in shifts", "Basic counting skills"],
    benefits: ["Cab Facility", "Meals", "PF & ESI", "Amazon Employee Benefits"],
    posted: "2 days ago",
    openings: 50,
    type: "Full Time",
  },
];

export const mockApplications = [
  {
    id: "1",
    job: "Retail Sales Executive",
    company: "Reliance Retail",
    appliedDate: "2024-03-01",
    status: "Interview",
    interviewDate: "2024-03-15",
    salary: "₹20,000",
  },
  {
    id: "2",
    job: "Customer Support Executive",
    company: "Concentrix",
    appliedDate: "2024-02-20",
    status: "Shortlisted",
    interviewDate: null,
    salary: "₹22,000",
  },
  {
    id: "3",
    job: "Data Entry Operator",
    company: "HDFC Bank",
    appliedDate: "2024-02-10",
    status: "Joined",
    interviewDate: "2024-02-20",
    salary: "₹15,500",
  },
  {
    id: "4",
    job: "Store Manager Trainee",
    company: "Big Bazaar",
    appliedDate: "2024-01-25",
    status: "Rejected",
    interviewDate: "2024-02-05",
    salary: "₹18,000",
  },
  {
    id: "5",
    job: "Sales Coordinator",
    company: "Titan Company",
    appliedDate: "2024-03-05",
    status: "Applied",
    interviewDate: null,
    salary: "₹19,000",
  },
];

export const mockNotifications = [
  {
    id: "1",
    type: "interview",
    title: "Interview Scheduled",
    message: "Your interview with Reliance Retail is scheduled for March 15, 2024 at 10:00 AM.",
    time: "2 hours ago",
    read: false,
  },
  {
    id: "2",
    type: "job",
    title: "New Job Match",
    message: "A new job matching your profile has been posted by Amazon India – Warehouse Associate.",
    time: "5 hours ago",
    read: false,
  },
  {
    id: "3",
    type: "application",
    title: "Application Shortlisted",
    message: "Congratulations! Your application for Customer Support Executive at Concentrix has been shortlisted.",
    time: "1 day ago",
    read: false,
  },
  {
    id: "4",
    type: "announcement",
    title: "Center Announcement",
    message: "VPMS Career Fair 2024 will be held on March 20 at Mumbai Central. 50+ companies participating.",
    time: "2 days ago",
    read: true,
  },
  {
    id: "5",
    type: "application",
    title: "Application Update",
    message: "Your application for Store Manager Trainee at Big Bazaar was not selected. Keep applying!",
    time: "3 days ago",
    read: true,
  },
  {
    id: "6",
    type: "job",
    title: "New Jobs Available",
    message: "5 new jobs in Healthcare sector matching your profile are now available.",
    time: "4 days ago",
    read: true,
  },
];

export const mockStats = {
  totalStudents: 2847,
  certifiedStudents: 2134,
  jobSeekers: 891,
  activeJobs: 156,
  applications: 3421,
  interviews: 445,
  placedStudents: 1678,
  retainedStudents: 1402,
};

export const mockPlacementTrend = [
  { month: "Oct", placed: 110, target: 130 },
  { month: "Nov", placed: 135, target: 140 },
  { month: "Dec", placed: 98, target: 120 },
  { month: "Jan", placed: 158, target: 150 },
  { month: "Feb", placed: 172, target: 160 },
  { month: "Mar", placed: 145, target: 170 },
];

export const mockSalaryDistribution = [
  { range: "< ₹15k", count: 180 },
  { range: "₹15–20k", count: 420 },
  { range: "₹20–25k", count: 350 },
  { range: "₹25–30k", count: 210 },
  { range: "> ₹30k", count: 90 },
];

export const mockPlacementByCenter = [
  { center: "Mumbai", placed: 320 },
  { center: "Delhi", placed: 280 },
  { center: "Bangalore", placed: 240 },
  { center: "Hyderabad", placed: 190 },
  { center: "Chennai", placed: 175 },
  { center: "Pune", placed: 160 },
  { center: "Kolkata", placed: 145 },
];

export const mockCourseWise = [
  { name: "Retail Sales", value: 35 },
  { name: "BPO", value: 22 },
  { name: "Healthcare", value: 15 },
  { name: "Electrical", value: 12 },
  { name: "Beauty", value: 10 },
  { name: "Others", value: 6 },
];

export const mockRecentApplications = [
  { student: "Priya Sharma", job: "Sales Executive", company: "Reliance Retail", date: "Today, 10:30 AM", status: "Shortlisted" },
  { student: "Rahul Verma", job: "Customer Support", company: "Concentrix", date: "Today, 9:15 AM", status: "Applied" },
  { student: "Anjali Patel", job: "Beauty Therapist", company: "VLCC", date: "Yesterday", status: "Interview" },
  { student: "Mohammed Iqbal", job: "Electrician", company: "L&T", date: "Yesterday", status: "Selected" },
  { student: "Sunita Kumari", job: "GDA", company: "Apollo Hospital", date: "2 days ago", status: "Applied" },
];

export const mockUpcomingInterviews = [
  { student: "Priya Sharma", company: "Reliance Retail", role: "Sales Executive", date: "Mar 15", time: "10:00 AM", mode: "Walk-in" },
  { student: "Rahul Verma", company: "Concentrix", role: "Customer Support", date: "Mar 16", time: "2:00 PM", mode: "Virtual" },
  { student: "Anjali Patel", company: "VLCC Wellness", role: "Beauty Therapist", date: "Mar 18", time: "11:00 AM", mode: "Walk-in" },
];

export const mockLatestJobs = [
  { company: "Amazon India", role: "Warehouse Associate", location: "Kolkata", salary: "₹22–28k", posted: "Today" },
  { company: "Apollo Hospitals", role: "GDA", location: "Chennai", salary: "₹14–18k", posted: "Today" },
  { company: "Concentrix", role: "Customer Support", location: "Delhi", salary: "₹20–25k", posted: "Yesterday" },
];
